apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
 name: beyondtrust-external-secret-namespace1
spec:
 refreshInterval: 5s
 
 secretStoreRef:
   kind: SecretStore
   name: secretstore-beyondtrust-namespace1
 
 target:
   name: my-beyondtrust-secret # name of secret to create in k8s secrets (etcd)
   creationPolicy: Owner
 
 data:
   - secretKey: secretKey
     remoteRef:
       key: system01/managed_account01
