apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
 name: secretstore-beyondtrust
spec:
 provider:
   beyondtrust:
    apiurl: https://example.com:443/BeyondTrust/api/public/v3/
    certificate:
      secretRef:
          name: bt-certificate
          key: ClientCertificate
    certificatekey:
      secretRef:
          name: bt-certificatekey
          key: ClientCertificateKey
    clientsecret:
      secretRef:
        name: bt-secret
        key: ClientSecret
    clientid:
      secretRef:
        name: bt-id
        key: ClientId
    retrievaltype: MANAGED_ACCOUNT
    verifyca: true
    clienttimeoutseconds: 45